### ISSUE TITLE
Add link to actual website

### ISSUE THREAD

**Issue by daniellecrobinson** [OpenCon-Cascadia/OpenCon-Cascadia.github.io#11]
https://opencon-cascadia.github.io/

**Comment by Bubblbu** [comment]
Where should this link go?

**Comment by Bubblbu** [comment]
@lwinfree I think that I don't have the rights to edit the repository description on the landing page of this repository. I think that Danielle was suggesting to update this one:

![image](https://user-images.githubusercontent.com/6946077/46927885-d44c8a80-d005-11e8-8982-cca2b1326775.png)

**Comment by lwinfree** [comment]
Oh thanks Asura - I got it updated now :-)
