### ISSUE TITLE
change blog to FAQs

### ISSUE THREAD

**Issue by lwinfree** [OpenCon-Cascadia/OpenCon-Cascadia.github.io#13]
- twitter hashtag
- gmail address
- speakers
- when will registration open

**Comment by lwinfree** [comment]
- childcare interest form
- lactation room info

**Comment by ashleyfarley** [comment]
I created an Appendix section in the Google Doc and there is a header for "FAQ Text" I think it will be easier to edit and draft responses there. Thanks for starting the list!

**Comment by Bubblbu** [comment]
Replaced the blog with a FAQ question and populated the page with Ashley's draft from the GDoc

https://opencon-cascadia.github.io/faq

**Comment by Bubblbu** [comment]
Updated the FAQ with actual Qs and As
