### ISSUE TITLE
Add Mission Statement to Site

### ISSUE THREAD

**Issue by ashleyfarley** [OpenCon-Cascadia/OpenCon-Cascadia.github.io#14]
I suggest placing this on the "About" page underneath the "What is OpenCascadia?" (which should be OpenCon Cascadia?)

"It is the mission of OpenCon Cascadia to build an inclusive, collaborative community, spanning all disciplines, domains, and research communities, by flattening hierarchical structures to provide a more open and equitable place for individuals to thrive. This Pacific Northwest community aims to support and foster mentorship, innovative solutions, collective projects, and energizing conversations on all things open, with a focus on building up young or new professionals."

**Comment by Bubblbu** [comment]
done!

https://opencon-cascadia.github.io/about

haven't looked much into formatting yet, but I think that we can do that seperately in one go as soon as we have got the content ready
