### ISSUE TITLE
add logo

### ISSUE THREAD

**Issue by lwinfree** [OpenCon-Cascadia/OpenCon-Cascadia.github.io#15]
see [issue](https://github.com/OpenCon-Cascadia/planning_in_the_open/issues/11)

**Comment by dconner3** [comment]
Can we add a credit somewhere to the artist who made the hex image? Maybe it could be hoover menu over the logo and/or somewhere on the about page?

**Comment by lwinfree** [comment]
I'll add it now! Thanks for catching that - I definitely want to credit Amy for her beautiful logo! :)

**Comment by lwinfree** [comment]
closed with https://github.com/OpenCon-Cascadia/OpenCon-Cascadia.github.io/pull/23
