### ISSUE TITLE
add keynotes

### ISSUE THREAD

**Issue by lwinfree** [OpenCon-Cascadia/OpenCon-Cascadia.github.io#17]
[Dr. Kadija Ferryman](https://datasociety.net/people/ferryman-kadija/) and [Dr. Leslie Chan](http://www.utsc.utoronto.ca/~chan/)

**Comment by dasaderi** [comment]
Can we add photo and bios? I can email them today to give them an update on our organization and ask for bios and headshot. @lwinfree

**Comment by lwinfree** [comment]
Yes @dasaderi please let me know when you get the pics & bios & I will add them :-)

**Comment by dasaderi** [comment]
@lwinfree @Bubblbu , I got pics and bios of the keynotes (you can find them in our shared organizer's drive in the "keynotes" folder). I'd put them in the home page, if possible. Also Leslie Chan said if it's too long we can trim it. Let me know if you need anything else relative to this issue. :)

**Comment by lwinfree** [comment]
Thx Daniela! Closed with https://github.com/OpenCon-Cascadia/OpenCon-Cascadia.github.io/pull/23
