### ISSUE TITLE
add organizers bios

### ISSUE THREAD

**Issue by lwinfree** [OpenCon-Cascadia/OpenCon-Cascadia.github.io#18]
(edit from Asura)

it would be amazing if you could format it like this + attach an image to the comment

```
---
name: name
affiliation: organisation
twitter: twitter_handle without @ (optional)
github: github_handle without @ (optional)
orcid: 1234-1234-1234-1234 (optional)
blog: URL (optional)
---

Short bio text
```

**Comment by ashleyfarley** [comment]
My bio & feel free to edit

"Over the past decade Ashley has worked in both academic and public libraries, focusing on digital inclusion and providing access to scholarly content. She has completed her Masters in Library and Information Sciences through the University of Washington’s Information School. Ashley is an Associate Officer of Knowledge and Research Services. In this capacity, she serves on the core Open Access team, focusing on the foundation’s Open Access Policy’s implementation. This includes the development of Chronos, and leading the implementation of Gates Open Research. This work has sparked a passion for open access, believing that freely accessible knowledge has the power to improve and save lives. @ashleydfarley"

![ashley farley headshot 1 med res](https://user-images.githubusercontent.com/22358242/47596354-a424b600-d93a-11e8-8485-ea7ce5eb5608.jpg)

**Comment by dasaderi** [comment]
My bio:
Daniela is neuroscience Ph.D. Candidate and community organizer passionate about bringing open practices into the world of academia as a means to improve reproducibility and collaboration. Her Ph.D. research combines _in vivo_ electrophysiology, behavior, and computational modeling to understand how sound is processed in the dynamic brain. Daniela is also a [Mozilla Fellow for Science 2018-2019](https://blog.mozilla.org/blog/2018/08/21/mozilla-announces-25-new-fellows-in-openness-science-and-tech-policy/). During her fellowship, she will be working on a project she co-founded in September 2017 called [PREreview](https://www.prereview.org), an open platform and community to facilitate the collaborative writing of preprint reviews and the training of early-career researchers in scientific peer review. Through this work, she hopes to foster a broader and much needed cultural change in the way science is evaluated and disseminated. Twitter: @Neurosarda; GitHub: @dasaderi 

![daniela-saderi-headshot](https://user-images.githubusercontent.com/13750121/47726433-b727d680-dc17-11e8-9035-c644336880ab.jpg)

**Comment by dconner3** [comment]
@lwinfree : (Not sure if this is formatted the way you want it. Feel free to change it or ask me to do so)

---
name: David Isaak
affiliation: Reed College
twitter: DavidCIsaak
github: dconner3
orcid: 0000-0002-9548-3855
---

A librarian with over ten years experience in digital, academic, and special libraries, David is currently the [Data Services Librarian](https://library.reed.edu/about/staff/isaak.html), at Reed College. There he helps coordinate the [Data@Reed Team](https://www.reed.edu/data-at-reed) and the [Federal Depository Library Program](https://www.fdlp.gov). David works with faculty and students to improve data information literacy, find and acquire existing datasets, write data management plans, and archive and cite data. He is also the library liaison to the Linguistics and Psychology departments.

![david_200x257_cms](https://user-images.githubusercontent.com/17661501/48744245-4aeb3200-ec1b-11e8-9f2f-4d7670824e44.jpg)

**Comment by LuciMoore** [comment]
---
name: Lucille Moore
affiliation: OHSU
twitter: @lucilleamoore
github: LuciMoore
---

Lucille Moore is a Ph.D. candidate in Neuroscience. Her research explores specialized neuronal communication and anatomical pathways of the central auditory system using _in vitro_ electrophysiology. Luci is passionate about creating a more equitable scientific and global community and deconstructing power dynamics created and upheld by ownership and accessibility of information. To this end, Luci advocates for open science at OHSU by educating her graduate community about open philosophy and practices. She also works as a founding member of the [Alliance for Visible Diversity in Science](http://a4vdis.weebly.com/) to promote recruitment, retention, and support of graduate students from historically underrepresented backgrounds in academia.    

![headshot](https://user-images.githubusercontent.com/25397699/48963159-aaaa4b80-ef41-11e8-8a5a-c6d7af28ac5b.png)

**Comment by dasaderi** [comment]
@Bubblbu I added Luci's bio to the team folder and her pic to the images folder, but for some reason she is not showing on the about page. What did I do wrong? Thank you!

**Comment by dasaderi** [comment]
I think I fixed it. The image needed to be a jpg and not png. Now I just need to cut it squared so that it shows as a circle and not an oval. :)

**Comment by dasaderi** [comment]
The other problem is that for some reason the twitter link does not actually link to Luci's page. Sorry can't figure out why.

**Comment by Bubblbu** [comment]
Images can be any format. Just change the path to the image file (with correct file ending in the markdown file) :) and yes. square images work better. it doesn't automatically crop them

and fixed the twitter/github links with e962ce9768c1036b33bb86efcc03c43be45cde21

**Comment by Bubblbu** [comment]
quick update if anyone still wants to add their profiles:

I've added the options to have icons for orcid and a personal blog/page if you prefer these over twitter/github.

**Template**
```
---
name: name
affiliation: organisation
twitter: twitter_handle without @ (optional)
github: github_handle without @ (optional)
orcid: 1234-1234-1234-1234 (optional)
blog: URL (optional)
---

Short bio text
```

**Comment by dconner3** [comment]
Great. I updated my comment above in this issue with my orcid. Thanks!

**Comment by theresacheng** [comment]
---
name: Theresa Cheng
affiliation: University of Oregon
twitter: cecily_cardew
github: theresacheng
orcid: 0000-0002-8557-565X
---

Theresa is a doctoral student in Psychology and an NIH/NCATS pre-doctoral fellow at the Oregon Clinical and Translational Research Institute. Her research explores stress, puberty, and social relationships during adolescence. She is passionate about open and reproducible scientific practices in neuroimaging and co-organizes the Eugene pod of 500 Women Scientists, a non-profit organization promoting diversity and public engagement in science.
![tc_headshot_072016](https://user-images.githubusercontent.com/22663671/51446950-86fb4b80-1ccd-11e9-9d3c-b284a6c0cf1f.jpg)

**Comment by LuciMoore** [comment]
Hi my bio text needs to be updated. Can you please replace what I have with:

Lucille Moore recently joined the Department of Neurology at Oregon Health & Science University as a Postdoctoral Scholar and ORCCAMIND Fellow. Her research will explore the potential for mindfulness-based intervention (Mindfulness Based Cognitive Therapy or MBCT adapted for pregnant women) to alter developing fetal brain systems via reduced stress and inflammation in the mother. Outside of research, Lucille is passionate about creating a more equitable scientific and global community and deconstructing power dynamics created by ownership of information. To this end, Lucille works as an open science advocate to promote open practices at her institution. She also works as a founding member of the Alliance for Visible Diversity in Science to promote recruitment, retention, and support of graduate students from historically underrepresented backgrounds in academia.

**Comment by pamelapierce** [comment]
Pam Pierce is the Repository Librarian at OHSU, where she leads the Library’s outreach for digital collections and oversees the  digital asset management system. Her work focuses on how digital images are used in marketing, historically and in contemporary efforts, as well as studying how users interact with and gain information from repositories. She was previously the Digital Library Coordinator and Archivist at the Theodore Roosevelt Center. 

![profile photo](https://user-images.githubusercontent.com/40672135/51777116-905f2c00-20b0-11e9-998b-69942fe55f50.jpg)

**Comment by rchampieux** [comment]
Jonathan Cain, MLIS is the Head of Data Services at the University of Oregon Libraries. He holds an MSLIS from Pratt Institute and holds an MA in Africana Studies from New York University and a BS in Anthropology from the College of Charleston. At the University of Oregon, Jonathan works directly with researchers implementing research data management best practices, open research practices, and adopting open source tools for data management, analysis, and sharing. He also the libraries’ liaison to the School of Planning, Public Policy, and Management, providing in-depth consultative reference services, collection development, and course-integrated instruction. Jonathan is building the Oregon Nonprofit Index as a member of the Mozilla Open Leaders Program (5th Cohort) and has served as the chair for the State Library of Oregon’s Library Services & Technology Act (LSTA) Program Advisory Committee. He also serves on the board of Oregon Black Pioneers, a nonprofit organization focusing on researching and providing education about the contributions of African Americans to Oregon history.
Social Media:
Twitter handle - @walesinterest
![jonathan_cain_2014](https://user-images.githubusercontent.com/15355483/51807150-34271400-2238-11e9-80a5-a95f2794e80d.jpg)

**Comment by rchampieux** [comment]
[JEBIO2019.docx](https://github.com/OpenCon-Cascadia/OpenCon-Cascadia.github.io/files/2800553/JEBIO2019.docx)
![jephoto5](https://user-images.githubusercontent.com/15355483/51807175-781a1900-2238-11e9-9ffa-18d45d4f4652.png)
