### ISSUE TITLE
add blog

### ISSUE THREAD

**Issue by lwinfree** [OpenCon-Cascadia/OpenCon-Cascadia.github.io#35]
@Bubblbu is working on writing a blog post. I'll wait to add a blog page to the site until we have content (or, Asura you can add the blog page once your post is ready :-) ).

**Comment by ashleyfarley** [comment]
@lwinfree @Bubblbu Could you please add this blog post to the website? https://docs.google.com/document/d/1PyuwIfbFS7OzYGzcRdjXmN5HoieptUhSMr5x1D9kJ0I/edit You should have access to the Google doc but let me know if you have any issues or questions. Really appreciate the help!

**Comment by Bubblbu** [comment]
Added the first blog post. https://opencon-cascadia.github.io/blog/speaker-highlight-leslie

**Comment by ashleyfarley** [comment]
Fantastic! Thanks so much. Looks great.

**Comment by lwinfree** [comment]
yay thanks @Bubblbu!!
