### ISSUE TITLE
add do-a-thon section

### ISSUE THREAD

**Issue by lwinfree** [OpenCon-Cascadia/OpenCon-Cascadia.github.io#44]
Once we have the text for the page from @rchampieux

**Comment by lwinfree** [comment]
and list the projects on the website as they come in

**Comment by rchampieux** [comment]
Hi @lwinfree I edited the website text for the do-a-thon, but haven't finished the form.  I'll finish this up in the AM.  Please feel free to edit the website text.

**Comment by rchampieux** [comment]
The text describing the OpenCon Cascadia do-a-thon text is ready to go, as well as the form (which the text links to).  Here is the form:
