### ISSUE TITLE
add speakers bios and headshots

### ISSUE THREAD

**Issue by dasaderi** [OpenCon-Cascadia/OpenCon-Cascadia.github.io#45]
Hi, I asked Tara Robertson for her headshot and bio. Do we have the same for other speakers? @rchampieux should we have the organizers who invited the speakers to contact them?  I can ask Carol. 

@Bubblbu and @lwinfree, here is Tara's bio and headshot
![taraprofile-small](https://user-images.githubusercontent.com/13750121/51126740-e0f1a200-17f1-11e9-8c17-442d72d8728c.jpg)

Tara Robertson is an intersectional feminist who uses data and research to advocate for equality and inclusion. Currently working as the Diversity & Inclusion Strategic Partner for Mozilla, she has more than 10 years experience making open source and tech communities more diverse and welcoming.

**Comment by rchampieux** [comment]
Thanks @dasaderi.  I think I already asked Carol, but told her not to worry about sending until she's back from Cuba.  Yes, let's ask our askers to do this.  I will get David Edwards, Douglas Tsoi's, and Jen Klaudinyi's.

**Comment by Bubblbu** [comment]
added an overview page for all speakers: https://opencon-cascadia.github.io/speakers/

Do we want to have that as an additional tab on the page navbar?

Each speakers also has an individual page including details (e.g. https://opencon-cascadia.github.io/speakers/letisha)

Also, added the option to provide the orcid to the personal profiles. this also applies to the OC (e.g. https://opencon-cascadia.github.io/team/asura)

**Comment by rchampieux** [comment]
This is awesome!  Thanks @Bubblbu.  I think we would add it as a tab on the nav bar, but let's wait until early next week, when it's more populated.

**Comment by lwinfree** [comment]
Thanks @Bubblbu!! I agree with Robin :-)

**Comment by dasaderi** [comment]
Thank you @Bubblbu. What I find confusing is that in the program page, it says Keynote speakers and then has bios for not only the keynote speakers Kadija and Leslie, but also some of the panelists. Maybe I'd add a title saying "Panel speakers"? I tried to do it, but I could not figure it out without screwing up things.

**Comment by Bubblbu** [comment]
@dasaderi thank you for pointing that out! I hadn't seen that :O will fix this today

> I tried to do it, but I could not figure it out without screwing up things.

and don't worry :D unfortunately there's no quick fix for that because the list is generated based on the data in a single folder. so I'll have to restructure a bit

(edit: fixed with #49)

**Comment by rchampieux** [comment]
Here is David Edward's bio:

David is a Scientific Programming and Communications Fellow at the Cancer Early Detection Advanced Research (CEDAR) center at OHSU, where he is developing a core infrastructure for writing support at CEDAR. Along with assisting CEDAR with scientific communication and writing education, he started the “Share Our Science” initiative to maximize knowledge-sharing from CEDAR’s research projects. This initiative is a collaborative institutional commitment to open science, and focuses on identifying relevant publishing platforms for CEDAR researchers to use and share their discoveries. In 2018, he earned his PhD in Cancer Biology at Oregon Health & Science University. Before that, he earned Bachelor’s degrees in Creative Writing and in Molecular Biosciences/Biotechnology from Arizona State University. 

Website:
![edwards david_flipped](https://user-images.githubusercontent.com/15355483/51416964-c5a7cf00-1b30-11e9-9d58-1737859b1c09.jpg)
 http://www.davidkedwardsv.com/.

**Comment by dasaderi** [comment]
Just reopened the issue as we need other speakers' bios and headshots. We still need: 
- Crystallee Crain 
- Douglas Tsoi 
- Jen Klaudinyi 
- Hannah Stepanek 
- Sanjay Srivastava 
- Carol Muñoz Nieves (already asked)

**Comment by rchampieux** [comment]
When we're ready to make the page live on the menu, we should update the program so speaker names like to their bios.

**Comment by dasaderi** [comment]
Yes, I think we can start now as we have several speakers' bios at hand. @Bubblbu I'll let you or @lwinfree do that as I'm not sure how you plan to organize that in the website. 
Thanks!

**Comment by Bubblbu** [comment]
webpage updated

**Comment by xolotl** [comment]
I added Hannah's bio and photo via https://github.com/OpenCon-Cascadia/OpenCon-Cascadia.github.io/pull/51

**Comment by rchampieux** [comment]
Hi @Bubblbu - here is Jen's bio and pic:

Jen Klaudinyi is a community college librarian and an open education coach and rabble-rouser. She has worked on OER initiatives for the past 9 years. Her current interests include the social justice opportunities afforded by open education, and she is excited to be leading a project to this end: the PCC Equity and Open Education Faculty Cohort.
![jen-klaudinyi](https://user-images.githubusercontent.com/15355483/51575743-32400800-1e68-11e9-8a45-2fe01e587976.jpg)

**Comment by dasaderi** [comment]
I added Nick Shokey, Jen, and Steph Wright's headshots and bios. Maybe worth adding two more "types" like "moderator" and "lightening talk"? @Bubblbu

**Comment by dasaderi** [comment]
Also, not sure why Jen's photo is an oval instead of a circle. :/

**Comment by Bubblbu** [comment]
@dasaderi 

> Also, not sure why Jen's photo is an oval instead of a circle. :/

The images need to be cropped to squares manually. Results are usually a lot better this way compared to images cropped weirdly by the code.

> Maybe worth adding two more "types" like "moderator" and "lightening talk"?

We can definitely do that! I haven't used that data for any layouting/formatting yet. But I can think of two options:

1. Keep the current layout and simply add the type to the overview list and/or speaker detail pages
2. We can based on the type create multiple lists on the "speakers" page. Keynotes, Moderation, Panelists, Lightning Talks

Both are relatively simple to implement. Not sure which one's nicer and/or more useful

**Comment by dasaderi** [comment]
Whatever is easiest. I think adding what is the "engagement type" of the speaker with the conference to their detail pages is fine, without creating more tabs. We will also need to link their names in the program to these pages.

Re to the image, I'm not sure either. I have not cropped any of the others. Weird.

**Comment by Bubblbu** [comment]
I've already added the links to the speaker pages to program.

> I have not cropped any of the others. Weird.

that was me ;) I usually cropped and downsized images

> Whatever is easiest. I think adding what is the "engagement type" of the speaker with the conference to their detail pages is fine, without creating more tabs.

I will look into that later today

**Comment by dasaderi** [comment]
Hi @Bubblbu did you change what it says under name for each speaker? I updated another lightening talk speaker, Ciera Martinez, and it says "panelist" under her name, presumably because the type is "panel". Is there a type "lightening"? Thanks!

**Comment by Bubblbu** [comment]
yes! there are four categories at the moment

- keynote
- panel
- moderation
- lightning

**Comment by dasaderi** [comment]
Thank you for fixing that. :)

**Comment by rchampieux** [comment]
![passportphoto2](https://user-images.githubusercontent.com/15355483/51807198-be6f7800-2238-11e9-9e26-2c38dffb79a6.jpg)
Douglas's Bio:  https://www.douglastsoi.com/
