### ISSUE TITLE
Add Mozilla office address to front page

### ISSUE THREAD

**Issue by dasaderi** [OpenCon-Cascadia/OpenCon-Cascadia.github.io#55]
@Bubblbu or @lwinfree could you please add the link to Mozilla office address in the front page? I want it to be super clear that the Meet & Green on Friday will not be at the CLSB.  

This is the address: 1120 NW Couch St #320, Portland, OR 97209. Currently it shows up only on the program. Thanks!

**Comment by dasaderi** [comment]
Oh and please also add 3rd floor.

**Comment by lwinfree** [comment]
closed with https://github.com/OpenCon-Cascadia/OpenCon-Cascadia.github.io/pull/57

**Comment by lwinfree** [comment]
could be prettier, but it will work for now ;-)
